CREATE TABLE LECTURERS (
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
NAME TEXT NOT NULL,
TITLE TEXT NOT NULL,
CAR_ID INT UNIQUE,
FOREIGN KEY(CAR_ID) REFERENCES CARS(ID));

CREATE TABLE CARS(
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
PLATE_NUMBER TEXT UNIQUE,
BRAND TEXT NOT NULL,
MODEL TEXT NOT NULL,
YEAR INT,
COLOR TEXT)

INSERT INTO CARS(PLATE_NUMBER, MODEL, BRAND, YEAR, COLOR)
VALUES ('89-989-101', 'fERRARI', 'TESTA ROCCA', 2022,' RED')

INSERT INTO CARS(PLATE_NUMBER, MODEL, BRAND, YEAR, COLOR)
VALUES ('11-454-33', 'PORCHE', 'COBRA', 2023,'BLACK')

INSERT INTO CARS(PLATE_NUMBER, MODEL, BRAND, YEAR, COLOR)
VALUES ('90-999-99', 'HONDA', 'CIVIC', 2020,'GREEN')

INSERT INTO LECTURERS(NAME, TITLE, CAR_ID)
VALUES ('DANNY', 'PR.', 1)